package me.lostandfound.model;
// Generated 2014-10-29 23:03:33 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * College generated by hbm2java
 */
@Entity
@Table(name = "college", schema = "public")
public class College implements java.io.Serializable {

	private int id;
	private String collegeName;
	private Set<Users> userses = new HashSet<Users>(0);

	public College() {
	}

	public College(int id, String collegeName) {
		this.id = id;
		this.collegeName = collegeName;
	}
	public College(int id, String collegeName, Set<Users> userses) {
		this.id = id;
		this.collegeName = collegeName;
		this.userses = userses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="college_seq",sequenceName="college_id_seq",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="college_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "college_name", nullable = false, length = 25)
	@NotNull
	@Length(max = 25)
	public String getCollegeName() {
		return this.collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
