package me.lostandfound.model;
// Generated 2014-11-6 17:37:03 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.CascadeType;
import org.hibernate.validator.NotNull;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", schema = "public")
public class Comment implements java.io.Serializable {

	private int id;
	private Messagess messagess;
	private String commentContent;
	private Boolean showContent;

	public Comment() {
	}

	public Comment(int id, Messagess messagess) {
		this.id = id;
		this.messagess = messagess;
	}
	public Comment(int id, Messagess messagess, String commentContent,
			Boolean showContent) {
		this.id = id;
		this.messagess = messagess;
		this.commentContent = commentContent;
		this.showContent = showContent;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="comment_seq",sequenceName="comment_id_seq",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="comment_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "messagess_id", nullable = false)
	@NotNull
	public Messagess getMessagess() {
		return this.messagess;
	}

	public void setMessagess(Messagess messagess) {
		this.messagess = messagess;
	}

	@Column(name = "comment_content")
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Column(name = "show_content")
	public Boolean getShowContent() {
		return this.showContent;
	}

	public void setShowContent(Boolean showContent) {
		this.showContent = showContent;
	}

}
