package me.lostandfound.model;
// Generated 2014-11-5 0:21:15 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Hope generated by hbm2java
 */
@Entity
@Table(name = "hope", schema = "public")
public class Hope implements java.io.Serializable {

	private int id;
	private String hopeName;

	public Hope() {
	}

	public Hope(int id, String hopeName) {
		this.id = id;
		this.hopeName = hopeName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "hope_name", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getHopeName() {
		return this.hopeName;
	}

	public void setHopeName(String hopeName) {
		this.hopeName = hopeName;
	}

}
